### ISSUE TITLE
Instructor Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jrshutske/unit-conversion-api#6]
-[ ] Please update your readme.md with your project scope/problem statement.  This should include your URIs. This guide will be helpful in ensuring they are properly constructed: https://blog.mwaysolutions.com/2014/06/05/10-best-practices-for-better-restful-api/.
-[ ] Be sure to include your project plan and time log to date.  Let me know when that is complete and I'll re-review.

**Comment by jrshutske** [comment]
For a project plan I create issues to lay out what needs to be done. Also added a timelog.md to /docs.

**Comment by pawaitemadisoncollege** [comment]
Scope looks good. Looking forward to seeing the final product!
